server:
  port: 80

#不把feign注册到eureka，他就是个客户端
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
        readTimeout: 5000 #指的是建立连接过后从服务器读取到可用资源所需的时间

logging:
  level:
    com.jx.springCloud.service.PaymentFeignService: DEBUG #feign日志以什么级别监控哪个接口