server:
  port: 8012

spring:
  application:
    name: cloud-consul-payment-service
  cloud:
    consul:
      host: 192.168.220.101
      port: 8500
      discovery:
        service-name: ${spring.application.name}