server:
  port: 80
spring:
  application:
    name: cloud-consul-order

  cloud:
    consul:
      host: 192.168.220.101
      port: 8500
      discovery:
        service-name: ${spring.application.name}